<a href="https://colab.research.google.com/github/tasnovahassan/PyTorch/blob/main/PytorchBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [285]:
import torch
print(torch.__version__)

2.6.0+cu124


In [286]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. using CPU")

GPU is available!
using GPU: Tesla T4


# creating tensor


In [287]:
#Using empty
torch.empty(2,3)

tensor([[2.8724e-18, 0.0000e+00, 5.1178e-02],
        [4.3311e-41, 2.8724e-18, 0.0000e+00]])

In [288]:
#check type
a=torch.empty(3,3)
print(a)
type(a)


tensor([[2.6933e-18, 0.0000e+00, 2.8780e-18],
        [0.0000e+00, 1.1210e-43, 0.0000e+00],
        [1.1210e-43, 0.0000e+00, 2.9067e-18]])


torch.Tensor

In [289]:
# using zeros
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [290]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [291]:
#using rand
torch.rand(2,3)

tensor([[0.1029, 0.4150, 0.7899],
        [0.9328, 0.3783, 0.8346]])

In [292]:
#using of seed
torch.manual_seed(42)
torch.rand(2,3)


tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [293]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [294]:
#arrange
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [295]:
#linespace
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [296]:
#eye
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [297]:
#full
torch.full((2,3),4)

tensor([[4, 4, 4],
        [4, 4, 4]])

# Tensor Shape

In [298]:
x=torch.tensor([[1,2,3],[4,5,6]])
x
x.shape

torch.Size([2, 3])

In [299]:
torch.empty_like(x)

tensor([[          575059440,           575922320,           303773208],
        [          536870912, 3180203458598089984, 8028074745930326560]])

In [300]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [301]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [302]:
torch.rand_like(x,dtype=torch.float64)

tensor([[0.0526, 0.5262, 0.4768],
        [0.9552, 0.9288, 0.0835]], dtype=torch.float64)

# Tensor data types

In [303]:
#find data type
x.dtype

torch.int64

In [304]:
#assign data type
torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]],dtype=torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [305]:
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# mathematical opeerations





#1.  Scaler

In [306]:
# Scaler operations
x = torch.rand(2,2)
x

tensor([[0.2666, 0.6274],
        [0.2696, 0.4414]])

In [307]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.0711, 0.3937],
        [0.0727, 0.1948]])

#2. element wise




In [308]:
# Element wise operation
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.2969, 0.8317, 0.1053],
        [0.2695, 0.3588, 0.1994]])
tensor([[0.5472, 0.0062, 0.9516],
        [0.0753, 0.8860, 0.5832]])


In [309]:
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b
# float div
a // b


tensor([[  0., 135.,   0.],
        [  3.,   0.,   0.]])

In [310]:
#abs
torch.abs(a)

tensor([[0.2969, 0.8317, 0.1053],
        [0.2695, 0.3588, 0.1994]])

In [311]:
#neg
torch.neg(a)

tensor([[-0.2969, -0.8317, -0.1053],
        [-0.2695, -0.3588, -0.1994]])

In [312]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [313]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [314]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [315]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [316]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])



# 3. Reduction operation

In [317]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[3., 4., 9.],
        [6., 2., 0.]])

In [318]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([16.,  8.])

In [319]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([4.5000, 3.0000, 4.5000])

In [320]:
# median
torch.median(e)

tensor(3.)

In [321]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [322]:
# product
torch.prod(e)

tensor(0.)

In [323]:
# standard deviation
torch.std(e)

tensor(3.1623)

In [324]:
# variance
torch.var(e)

tensor(10.)

In [325]:
# argmax
torch.argmax(e)

tensor(2)

In [326]:

# argmin
torch.argmin(e)

tensor(5)

# 4. Matrix operations

In [327]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[6, 2, 7],
        [9, 7, 3]])
tensor([[3, 4],
        [3, 7],
        [0, 9]])


In [328]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[ 24, 101],
        [ 48, 112]])

In [329]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [330]:
# transpose
torch.transpose(f, 0, 1)

tensor([[6, 9],
        [2, 7],
        [7, 3]])

In [331]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[0., 9., 6.],
        [9., 5., 4.],
        [8., 8., 6.]])

In [332]:
# determinant
torch.det(h)

tensor(-6.0000)

In [333]:
# inverse
torch.inverse(h)

tensor([[  0.3333,   1.0000,  -1.0000],
        [  3.6667,   8.0000,  -9.0000],
        [ -5.3333, -12.0000,  13.5000]])



# 5. Comparison operations

In [334]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[0, 0, 0],
        [0, 1, 3]])
tensor([[0, 1, 1],
        [7, 9, 4]])


In [335]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to
i>=j
# less than equal to
i<=j

tensor([[True, True, True],
        [True, True, True]])

# 6. Special functions

In [336]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[3., 8., 9.],
        [3., 7., 8.]])

In [337]:
# log
torch.log(k)

tensor([[1.0986, 2.0794, 2.1972],
        [1.0986, 1.9459, 2.0794]])

In [338]:
# exp
torch.exp(k)

tensor([[  20.0855, 2980.9580, 8103.0840],
        [  20.0855, 1096.6332, 2980.9580]])

In [339]:
# sqrt
torch.sqrt(k)

tensor([[1.7321, 2.8284, 3.0000],
        [1.7321, 2.6458, 2.8284]])

In [340]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.9997, 0.9999],
        [0.9526, 0.9991, 0.9997]])

In [341]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.5000, 0.7311, 0.7311],
        [0.5000, 0.2689, 0.2689]])

In [342]:
# relu
torch.relu(k)

tensor([[3., 8., 9.],
        [3., 7., 8.]])

# New section

# Inplace Operations

In [343]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035]])
tensor([[0.3813, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])


In [344]:
m.add_(n)

tensor([[1.2968, 1.0278, 0.2707],
        [1.0130, 0.9503, 1.4092]])

In [345]:
m

tensor([[1.2968, 1.0278, 0.2707],
        [1.0130, 0.9503, 1.4092]])

In [346]:
n

tensor([[0.3813, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])

In [347]:
torch.relu(m)

tensor([[1.2968, 1.0278, 0.2707],
        [1.0130, 0.9503, 1.4092]])

In [348]:
m.relu_()

tensor([[1.2968, 1.0278, 0.2707],
        [1.0130, 0.9503, 1.4092]])

In [349]:
m

tensor([[1.2968, 1.0278, 0.2707],
        [1.0130, 0.9503, 1.4092]])

# Copying a Tensor

In [350]:
a = torch.rand(2,3)
a

tensor([[0.3725, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578]])

In [351]:
b = a

In [352]:
b

tensor([[0.3725, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578]])

In [353]:
a[0][0] = 0

In [354]:
a

tensor([[0.0000, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578]])

In [355]:
b

tensor([[0.0000, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578]])

In [356]:
id(a)

132745713271440

In [357]:
id(b)

132745713271440

In [358]:
b = a.clone()

In [359]:
a

tensor([[0.0000, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578]])

In [360]:
b

tensor([[0.0000, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578]])

In [361]:
a[0][0] = 10

In [362]:
a

tensor([[10.0000,  0.7980,  0.8399],
        [ 0.1374,  0.2331,  0.9578]])

In [363]:
b

tensor([[0.0000, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578]])

In [364]:
id(a)

132745713271440

In [365]:
id(b)

132745713843760

#tensor operation on GPU

In [366]:
torch.cuda.is_available()

True

In [367]:
device= torch.device('cuda')

In [368]:
#creating a new tensor on GPU
torch.rand((2,3),device = device)

tensor([[0.6130, 0.0101, 0.3984],
        [0.0403, 0.1563, 0.4825]], device='cuda:0')

In [369]:
#moving an existing tensor to GPU
a = torch.rand((2,3))
b = a.to(device)

In [370]:
b+5

tensor([[5.3313, 5.3227, 5.0162],
        [5.2137, 5.6249, 5.4340]], device='cuda:0')

# Reshaping Tensors


In [371]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [372]:
#reshape
a.reshape(2,8)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [373]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [374]:
#permute
a.permute(1,0)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [375]:
b = torch.rand(2,3,4)
b

tensor([[[0.1371, 0.5117, 0.1585, 0.0758],
         [0.2247, 0.0624, 0.1816, 0.9998],
         [0.5944, 0.6541, 0.0337, 0.1716]],

        [[0.3336, 0.5782, 0.0600, 0.2846],
         [0.2007, 0.5014, 0.3139, 0.4654],
         [0.1612, 0.1568, 0.2083, 0.3289]]])

In [376]:
b.permute(2,0,1).shape


torch.Size([4, 2, 3])

In [377]:
#unsqueeze
c = torch.rand(226,226,3) #img size
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [378]:
#squeeze
d = torch.rand(1,226,226,3)
d.squeeze(0).shape

torch.Size([226, 226, 3])


# NumPy and Pytorch

In [379]:
import numpy as np

In [380]:
a = torch.rand(2,3)
a

tensor([[0.6606, 0.8834, 0.0846],
        [0.2261, 0.0546, 0.7178]])

In [381]:
b = a.numpy()

In [382]:
b

array([[0.660554  , 0.88339216, 0.08461815],
       [0.22612566, 0.05457115, 0.7177641 ]], dtype=float32)

In [383]:
type(b)

numpy.ndarray

In [384]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [385]:
torch.from_numpy(c)

tensor([[1, 2, 3],
        [4, 5, 6]])